name: docker cd
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
#     runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: docker login
      env:
        USER: ${{ secrets.DOCKER_USERNAME }}
        PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u "$USER" -p "$PASS"
    - name: env setup
      run: test -f .env || cp .env.sample .env
    - name: build images
      run: docker-compose up --build -d
    - name: docker push
      run: docker-compose push
